


console.log(1+1);

try{
    hola();
}catch(error){
    console.log(`Error tipo: ${error}-------- Esa funci√≥n no existe`);
}

console.log(2+2);